### ISSUE TITLE
Wrong URL - should be oauth, is auth

### ISSUE THREAD

**Issue by ndzoesch** [shopware/store-api-reference#43]
There is a typo at several places in the documentation.

Example: [configure-oauth-in-a-rest-client](https://shopware.stoplight.io/docs/admin-api/twpxvnspkg3yu-quick-start-guide#configure-oauth-in-a-rest-client)

- URL in the example: `http://localhost/api/auth/token`
- Should be: `http://localhost/api/oauth/token`

**Comment by sushmangupta** [comment]
Thanks for reporting. The issue is no longer existing 👍
