### ISSUE TITLE
Doc says API key instead of bearer token

### ISSUE THREAD

**Issue by ndzoesch** [shopware/store-api-reference#44]
This happens at multiple places in the docs.

Example: [creating-a-document-type]( https://shopware.stoplight.io/docs/admin-api/3be386a26c0f9-overview#creating-a-document-type)

It states `Bearer Your_API_Key` for auth - but the Bearer token is not the API key iirc.

**Comment by sushmangupta** [comment]
Thanks for reporting. You are right, and it has been changed to `Bearer YOUR_ACCESS_TOKEN` and hence closing this issue. 👍
